# このワークフローはGitHubによって認定されていないアクションを使用します。
# それらはサードパーティによって提供され、
# 別個の利用規約、プライバシーポリシー、
# サポートドキュメンテーションが適用されます。

name: Weekly Team Sync
on:
  schedule:
    - cron: * * * * * # 毎週水曜AM10時（UTCなので+9）

jobs:
  create_issue:
    name: Create 1on1 issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      # Repo code checkout required if `template` is used
      - name: Checkout
        uses: actions/checkout@v2

      # https://stackoverflow.com/a/60942437
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y/%m/%d')"

      - name: Create team sync issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          title: 1on1 - ${{ steps.date.outputs.date }}
          body: |
            ### Agenda

            - [ ] Start the recording
            - [ ] Check-ins
            - [ ] Discussion points
            - [ ] Post the recording

            ### Discussion Points
            Add things to discuss below

            - [Work this week](https://github.com/orgs/github/projects/3)
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}